---
- hosts: leaf_switches
  connection: local
  gather_facts: no

  roles:
    - { role: configure_layer2, tags: ['layer2'] }
    - { role: configure_layer3, tags: ['layer3'] }
    - { role: configure_bgp, tags: ['bgp'] }