---
  - name: Configure BGP process parameters
    eos_template:
      src: bgp_process.j2
      provider: "{{ eos_connection }}"
      #force: yes

  - name: Configure BGP neighbors
    eos_template:
      src: bgp_neighbors.j2
      provider: "{{ eos_connection }}"
      #force: yes

  - name: Configure BGP advertisements
    eos_template:
      src: bgp_networks.j2
      provider: "{{ eos_connection }}"
      #force: yes
