---
  - name: Configure BGP process parameters
    eos_template:
      src: bgp_process.j2
      provider: "{{ eos_connection }}"
    when: bgp_as is defined

  - name: Configure BGP neighbors
    eos_template:
      src: bgp_neighbors.j2
      provider: "{{ eos_connection }}"
    when: bgp_neighbors is defined

  - name: Configure BGP advertisements
    eos_template:
      src: bgp_networks.j2
      provider: "{{ eos_connection }}"
    when: bgp_networks is defined